
version: '3'

services:

  dev:
    build: .
    env_file:
      - build/dev.env
    volumes:
      - ./code:/code
      - ./data:/data
    ports:
      - '8888:8888'

  prod:
    build: .
    image: dclure/sent-order
